# Generated by Django 2.0.5 on 2018-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_manager', '0001_initial'),
        ('vouchers_manager', '0001_initial'),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单编号')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('amount', models.FloatField(verbose_name='订单金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('program', models.ForeignKey(on_delete=None, to='shop_manager.MassageProgram', verbose_name='项目')),
                ('shop', models.ForeignKey(on_delete=None, to='shop_manager.Shop', verbose_name='预约门店')),
                ('technician', models.ForeignKey(on_delete=None, to='shop_manager.Technician', verbose_name='理疗师')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
                ('voucher', models.ForeignKey(on_delete=None, to='vouchers_manager.Vouchers', verbose_name='使用代金券')),
            ],
            options={
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
