# Generated by Django 2.0.5 on 2018-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单'},
        ),
    ]
