# Generated by Django 2.0.5 on 2018-05-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0001_initial'),
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name_plural': '预约记录',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='program',
        ),
        migrations.AddField(
            model_name='order',
            name='program',
            field=models.ManyToManyField(to='shop_manager.MassageProgram', verbose_name='项目'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='technician',
        ),
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ManyToManyField(to='shop_manager.Technician', verbose_name='理疗师'),
        ),
        migrations.AddField(
            model_name='reservationrecord',
            name='order',
            field=models.ForeignKey(on_delete=None, to='order_manager.Order'),
        ),
        migrations.AddField(
            model_name='reservationrecord',
            name='program',
            field=models.ForeignKey(on_delete=None, to='shop_manager.MassageProgram', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='reservationrecord',
            name='technician',
            field=models.ForeignKey(on_delete=None, to='shop_manager.Technician', verbose_name='理疗师'),
        ),
    ]
