# Generated by Django 2.0.5 on 2018-05-26 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_auto_20180526_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='program',
            field=models.ManyToManyField(blank=True, to='shop_manager.MassageProgram', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technician',
            field=models.ManyToManyField(blank=True, to='shop_manager.Technician', verbose_name='理疗师'),
        ),
    ]
