# Generated by Django 2.0.5 on 2018-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0003_auto_20180526_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrecord',
            name='order',
            field=models.ForeignKey(on_delete=None, to='order_manager.Order', verbose_name='订单编号'),
        ),
    ]
