# Generated by Django 2.0.5 on 2018-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_auto_20180526_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.FloatField(default=0, verbose_name='使用余额'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='vouchers_manager.Vouchers', verbose_name='使用代金券'),
        ),
    ]
