# Generated by Django 2.0.5 on 2018-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0005_auto_20180529_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
        migrations.AddField(
            model_name='order',
            name='need_pay',
            field=models.FloatField(default=0, verbose_name='支付金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='1', max_length=32, verbose_name='充值方式(1=余额,2=微信)'),
        ),
    ]
