# Generated by Django 2.0.5 on 2018-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0006_auto_20180529_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='1', max_length=32, verbose_name='充值方式(0=余额,1=微信)'),
        ),
    ]
