# Generated by Django 2.0.5 on 2018-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0007_auto_20180530_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='0', max_length=32, verbose_name='充值方式(0=余额,1=微信)'),
        ),
    ]
