# Generated by Django 2.0.5 on 2018-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已经使用')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='领取日期')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='所属用户')),
            ],
            options={
                'verbose_name_plural': '用户代金券',
            },
        ),
        migrations.CreateModel(
            name='VouchersManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='抵扣金额')),
                ('effective_time', models.DateTimeField(verbose_name='有效期至')),
                ('use_shop', models.ManyToManyField(to='shop_manager.Shop', verbose_name='所属门店')),
            ],
            options={
                'verbose_name_plural': '代金券管理',
            },
        ),
        migrations.AddField(
            model_name='vouchers',
            name='voucher',
            field=models.ForeignKey(on_delete=None, to='vouchers_manager.VouchersManager', verbose_name='所属代金券'),
        ),
    ]
