# Generated by Django 2.0.5 on 2018-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers_manager', '0003_vouchers_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchersmanager',
            name='use_shop',
        ),
    ]
