# Generated by Django 2.0.5 on 2018-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers_manager', '0006_auto_20180524_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersmanager',
            name='belong_shop',
            field=models.ManyToManyField(blank=True, to='shop_manager.Shop', verbose_name='所属门店'),
        ),
    ]
