# Generated by Django 2.0.5 on 2018-05-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers_manager', '0007_auto_20180529_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchersmanager',
            name='is_issue',
            field=models.BooleanField(default=False, verbose_name='是否发放(默认发放最近的一个)'),
        ),
    ]
