# Generated by Django 2.0.5 on 2018-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers_manager', '0008_vouchersmanager_is_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchersmanager',
            name='is_issue',
            field=models.BooleanField(default=False, verbose_name='是否发放(如果勾选多个,默认发放ID最大的)'),
        ),
    ]
