# Generated by Django 2.0.5 on 2018-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default=None, max_length=32, null=True, verbose_name='手机号')),
                ('wx_id', models.CharField(max_length=64, verbose_name='微信OPENID')),
                ('balance', models.FloatField(default=0, verbose_name='余额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='ExpendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='消费金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('program', models.ForeignKey(default=None, on_delete=None, to='shop_manager.MassageProgram', verbose_name='项目')),
                ('shop', models.ForeignKey(on_delete=None, to='shop_manager.Shop', verbose_name='消费门店')),
                ('technician', models.ForeignKey(default=None, on_delete=None, to='shop_manager.Technician', verbose_name='调理师')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '消费记录',
            },
        ),
        migrations.CreateModel(
            name='MsgCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32, verbose_name='获取验证码手机号')),
                ('msg_code', models.PositiveIntegerField(verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='验证码创建时间')),
            ],
            options={
                'verbose_name_plural': '验证码表',
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='充值金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '充值记录',
            },
        ),
    ]
