# Generated by Django 2.0.5 on 2018-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_manager', '0001_initial'),
        ('vouchers_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32, verbose_name='手机号')),
                ('wx_id', models.CharField(max_length=64, verbose_name='微信ID')),
                ('balance', models.FloatField(verbose_name='余额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('vouchers', models.ManyToManyField(to='vouchers_manager.Vouchers', verbose_name='代金券')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.CreateModel(
            name='ExpendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='消费金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='消费时间')),
                ('shop', models.ForeignKey(on_delete=None, to='shop_manager.Shop', verbose_name='消费门店')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '消费记录',
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='充值金额')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '充值记录',
            },
        ),
    ]
