# Generated by Django 2.0.5 on 2018-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vouchers',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='vouchers_manager.Vouchers', verbose_name='代金券'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wx_id',
            field=models.CharField(max_length=64, verbose_name='微信OPENID'),
        ),
    ]
