# Generated by Django 2.0.5 on 2018-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechargerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='RechargeRecord',
        ),
    ]
