# Generated by Django 2.0.5 on 2018-05-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_auto_20180518_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vouchers',
            field=models.ManyToManyField(blank=True, default=None, to='vouchers_manager.Vouchers', verbose_name='代金券'),
        ),
    ]
