# Generated by Django 2.0.5 on 2018-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0004_auto_20180529_1144'),
        ('user_manager', '0002_auto_20180530_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendrecord',
            name='program',
        ),
        migrations.AddField(
            model_name='expendrecord',
            name='program',
            field=models.ManyToManyField(default=None, to='shop_manager.MassageProgram', verbose_name='项目'),
        ),
        migrations.RemoveField(
            model_name='expendrecord',
            name='technician',
        ),
        migrations.AddField(
            model_name='expendrecord',
            name='technician',
            field=models.ManyToManyField(default=None, to='shop_manager.Technician', verbose_name='调理师'),
        ),
    ]
