# Generated by Django 2.0.5 on 2018-05-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20180530_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendrecord',
            name='program',
        ),
        migrations.RemoveField(
            model_name='expendrecord',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='expendrecord',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='expendrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpendRecord',
        ),
    ]
