# Generated by Django 2.0.5 on 2018-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_auto_20180530_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
