# Generated by Django 2.0.5 on 2018-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='technician',
        ),
        migrations.AddField(
            model_name='technician',
            name='belong_shop',
            field=models.ForeignKey(default=None, on_delete=None, to='shop_manager.Shop', verbose_name='所属门店'),
        ),
    ]
