# Generated by Django 2.0.5 on 2018-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageprogram',
            name='technician',
            field=models.ManyToManyField(to='shop_manager.Technician', verbose_name='技师'),
        ),
        migrations.AddField(
            model_name='shop',
            name='technician',
            field=models.ManyToManyField(to='shop_manager.Technician', verbose_name='技师'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=64, verbose_name='城市名称'),
        ),
    ]
