# Generated by Django 2.0.5 on 2018-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0002_auto_20180526_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='belong_shop',
            field=models.ForeignKey(default=None, null=True, on_delete=None, to='shop_manager.Shop', verbose_name='所属门店'),
        ),
    ]
