# Generated by Django 2.0.5 on 2018-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0003_auto_20180526_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massageprogram',
            name='technician',
            field=models.ManyToManyField(blank=True, to='shop_manager.Technician', verbose_name='调理师'),
        ),
    ]
