# Generated by Django 2.0.5 on 2018-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manager', '0004_auto_20180529_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload', verbose_name='项目照片'),
        ),
    ]
