# Generated by Django 2.0.5 on 2018-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='充值金额')),
                ('record_number', models.CharField(max_length=64, verbose_name='充值订单号')),
                ('is_pay', models.BooleanField(default=False, verbose_name='支付状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='充值日期')),
                ('user', models.ForeignKey(on_delete=None, to='user_manager.Customer', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '充值订单',
            },
        ),
    ]
