# Generated by Django 2.0.5 on 2018-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_manager', '0002_rechargeactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeactive',
            name='recharge_amount',
            field=models.FloatField(verbose_name='充值金额'),
        ),
    ]
